### ISSUE TITLE
Log into remote ftp server

### ISSUE THREAD

**Issue by prmudgal** [swethavs/Agile510#6]

**Comment by mpooja1** [comment]
Moving into Dev State.. Attaching error sheet..

[testcases.pdf](https://github.com/swethavs/Agile510/files/368115/testcases.pdf)

**Comment by PardeeXi** [comment]
1. case: provide all correct login credential
             PASS
2. case: incorrect login name 
             FAIL, error messege thrown, should be handle more gracefully
   com.jcraft.jsch.JSchException: Auth fail
   at com.jcraft.jsch.Session.connect(Session.java:452)
   at SessionController.setUpConnection(SessionController.java:37)
   at FTPConnectDemo.main(FTPConnectDemo.java:31)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
3. case: incorrect login password 
             FAIL, error messege thrown, should be handle more gracefully
   com.jcraft.jsch.JSchException: Auth fail
   at com.jcraft.jsch.Session.connect(Session.java:452)
   at SessionController.setUpConnection(SessionController.java:37)
   at FTPConnectDemo.main(FTPConnectDemo.java:31)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
4. case: input q should exit the program 
             FAIL, error messege thrown, 
   Exception in thread "main" java.lang.NullPointerException
   at SessionController.closeSession(SessionController.java:196)
   at FTPConnectDemo.main(FTPConnectDemo.java:37)
   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   at java.lang.reflect.Method.invoke(Method.java:483)
   at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
